# Generated by Django 5.2.5 on 2025-09-01 14:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo del cliente', max_length=100)),
                ('email', models.EmailField(help_text='Email único del cliente', max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de contacto', max_length=20, null=True)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, help_text='Saldo actual del cliente', max_digits=12)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de registro del cliente')),
                ('activo', models.BooleanField(default=True, help_text='Cliente activo en el sistema')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistorialAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('consulta', 'Consulta'), ('creacion', 'Creación'), ('actualizacion', 'Actualización'), ('pago', 'Pago'), ('ai_tool', 'AI Tool Call')], help_text='Tipo de acción realizada', max_length=20)),
                ('descripcion', models.TextField(help_text='Descripción de la acción')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP desde donde se realizó la acción', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos adicionales en formato JSON')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de la acción')),
                ('cliente', models.ForeignKey(blank=True, help_text='Cliente relacionado (si aplica)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='customer_support.cliente')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que realizó la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Acción',
                'verbose_name_plural': 'Historial de Acciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto del pago', max_digits=12)),
                ('descripcion', models.CharField(blank=True, help_text='Descripción/concepto del pago', max_length=200)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta de Crédito/Débito'), ('transferencia', 'Transferencia Bancaria'), ('cheque', 'Cheque')], default='transferencia', help_text='Método de pago utilizado', max_length=20)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha del pago')),
                ('cliente', models.ForeignKey(help_text='Cliente que realiza el pago', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='customer_support.cliente')),
                ('procesado_por', models.ForeignKey(blank=True, help_text='Usuario que procesó el pago', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título descriptivo del problema', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción detallada del problema')),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_proceso', 'En Proceso'), ('pendiente', 'Pendiente Cliente'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], default='abierto', help_text='Estado actual del ticket', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', help_text='Prioridad del ticket', max_length=20)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de creación del ticket')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización')),
                ('fecha_resolucion', models.DateTimeField(blank=True, help_text='Fecha de resolución del ticket', null=True)),
                ('asignado_a', models.ForeignKey(blank=True, help_text='Agente asignado al ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(help_text='Cliente que reporta el ticket', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='customer_support.cliente')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
